### PR TITLE
login/register switch function

### PR DESCRIPTION
**Pull request by dylangorman**
Removed Home page and created switch between login and register ready for some sweet CSS!!! Watch this space!!

### CODE REVIEW

**Comment by DavidH1982** [comment]
I think there is a problem, landing page enter button still has the link to /home, so now you've gotten rid of home there is nowhere to go! Need to link enter with login/register

**Review by strawberette — COMMENTED** [review]
Please change line 35 in Register.jsx redirecting it to login

**Review by strawberette — APPROVED** [review]
all good to go!

**Comment by dylangorman** [comment]
all working

**Pull request merged**
